# Cloud Native Buildpacks 配置文件
# https://buildpacks.io/docs/reference/config/project-descriptor/

[project]
id = "random-image-api"
name = "随机图片API系统"
version = "1.0.0"

# 指定构建器
[build]
# 使用 Paketo Buildpacks（推荐用于 Node.js）
builder = "paketobuildpacks/builder:base"

# 或使用 Heroku Buildpacks
# builder = "heroku/builder:22"

# 环境变量
[[build.env]]
name = "NODE_ENV"
value = "production"

[[build.env]]
name = "NPM_CONFIG_PRODUCTION"
value = "true"

# 构建时环境变量
[[build.env]]
name = "BP_NODE_RUN_SCRIPTS"
value = "false"

# 包含的文件
include = [
  "server-secure.js",
  "package*.json",
  "vue-simple/**",
  ".env.example"
]

# 排除的文件
exclude = [
  "node_modules",
  "vue-simple/node_modules",
  "dist",
  "*.db",
  ".env",
  "*.md",
  ".git"
]

# 构建包配置
[[build.buildpacks]]
id = "paketo-buildpacks/node-engine"

[[build.buildpacks]]
id = "paketo-buildpacks/npm-install"

[[build.buildpacks]]
id = "paketo-buildpacks/npm-start"

# 定义进程类型
[processes]
web = "node server-secure.js"